### ISSUE TITLE
Try yo test example error with npm start

### ISSUE THREAD

**Issue by nicolasTorrell** [RobertSasak/react-native-openalpr#118]
When i try to do the npm start and connect to the url it gives this message, it's there something i'm missing?
Error: Unable to resolve module `./index.android` from ``: 

None of these files exist:
  * index.android(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index.android\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\lib\transformHelpers.js:267:42
    at Server.<anonymous> (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\Server.js:99:24)
    at _next (C:\Users\ntorrell\Desktop\ocrREact\react-native-openalpr\example\node_modules\metro\src\Server.js:119:9)

**Comment by RobertSasak** [comment]
It sounds like an metro installation issue. I would start by cloning repo into new folder, navigate to _example_ folder and installed all the dependencies by running _yarn_. Then you can try to run _react-native run-android_ If is still does not work, please provide more information regarding what version of NPM and react-native are installed.

**Comment by Turing311** [comment]
Same issue here.
How can resolve it?

**Comment by RobertSasak** [comment]
@Turing311 Without more information it is not possible to help you. Please start with the example folder. Make it run there and then try it in your own project.
