### ISSUE TITLE
I met some Errors on Example Project

### ISSUE THREAD

**Issue by Icarus0420** [RobertSasak/react-native-openalpr#127]
Hi.
I have some errors on example project using react-native-openalpr.
Error is following:

"error: bundling failed: Error: Unable to resolve module `react-native-openalpr` from `App.js`: react-native-openalpr could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\workspace\ReactNative\react-native-openalpr\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 BUNDLE  [android, dev] ./index.js ▓▓░░░░░░░░░░░░░░ 12.8% (122/341), failed.

::ffff:127.0.0.1 - - [27/Oct/2021:09:56:42 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
"

please help me..
I have double checked steps of that..

**Comment by RobertSasak** [comment]
Closed for inactivity.
