### ISSUE TITLE
When i try to open the app it crashes

### ISSUE THREAD

**Issue by Skeetfly** [RobertSasak/react-native-openalpr#27]
When i try to open the app it crashes and when i check my logcat it gives me this
`12-13 23:11:58.570 7386-7427/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: HandlerThread
                                                                  Process: com.awesomeproject, PID: 7386
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/base.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/lib/x86, /system/fake-libs, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/base.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.awesomeproject-u_BQPWSNgToWJy9vA39Etw==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libopenalpr-native.so"
                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                      at java.lang.System.loadLibrary(System.java:1657)
                                                                      at org.openalpr.AlprJNIWrapper.<clinit>(AlprJNIWrapper.java:9)
                                                                      at org.openalpr.OpenALPR$Factory.create(OpenALPR.java:80)
                                                                      at com.cardash.openalpr.ALPR.executeRecognition(ALPR.java:119)
                                                                      at com.cardash.openalpr.ALPR.access$100(ALPR.java:35)
                                                                      at com.cardash.openalpr.ALPR$1.handleMessage(ALPR.java:55)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by Bobozee** [comment]
I have experienced the same issue but only on very old Android hardware.

**Comment by RobertSasak** [comment]
Closing, as it is an old issue.
