### ISSUE TITLE
Android Crash - broken pipe

### ISSUE THREAD

**Issue by tjlondon-npauctions** [RobertSasak/react-native-openalpr#62]
Thanks for the work you've put into this. Looks really promising.

However, I'm struggling to get the Example project working on Android, it crashes as soon as the camera mounts with the following. Can anyone give me any pointers?

```
2019-10-06 17:55:31.544 5323-5323/com.rnopenalprexample E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2019-10-06 17:55:33.077 5323-5380/com.rnopenalprexample E/AndroidRuntime: FATAL EXCEPTION: HandlerThread
    Process: com.rnopenalprexample, PID: 5323
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/base.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_resources_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/base.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.rnopenalprexample-Z4YXITY-fTiLbe2Asr_GVQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]] couldn't find "libopenalpr-native.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.openalpr.AlprJNIWrapper.<clinit>(AlprJNIWrapper.java:9)
        at org.openalpr.OpenALPR$Factory.create(OpenALPR.java:80)
        at com.cardash.openalpr.ALPR.executeRecognition(ALPR.java:119)
        at com.cardash.openalpr.ALPR.access$100(ALPR.java:35)
        at com.cardash.openalpr.ALPR$1.handleMessage(ALPR.java:55)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by RobertSasak** [comment]
Android part of the module is not working as there are no 64 bit libraries.
https://github.com/RobertSasak/react-native-openalpr/issues/61

For reference: https://github.com/RobertSasak/react-native-openalpr/blob/1ae6fe8eabdcc548aa1721704222f6498e7d8c2a/android/libraries/opencv/src/org/opencv/android/StaticHelper.java#L34
