### ISSUE TITLE
error on run http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

### ISSUE THREAD

**Issue by langpp** [RobertSasak/react-native-openalpr#70]
i getting error on run http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false in my localhost. this is error

Error: Unable to resolve module `./index.android` from ``: 

None of these files exist:
  * index.android(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index.android\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\lib\transformHelpers.js:267:42
    at Server.<anonymous> (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\Server.js:1088:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\Server.js:99:24)
    at _next (C:\react-native\module\react-native-openalpr\example\node_modules\metro\src\Server.js:119:9)

**Comment by im-amir** [comment]
Here is the fix:
- After "step 4", if you have run "npm start", terminate it.
- then in `example` directory, run this command:
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
then in `example` directory, run:
`cd android && gradlew clean`
`cd .. && react-native run-android`
