### ISSUE TITLE
Out of memory error :::: Mat.n_clone

### ISSUE THREAD

**Issue by Balasnest** [RobertSasak/react-native-openalpr#98]
Any idea? Facing this while calling process method in onCameraFrame. How to resolve this problem?

Looks like cloning Mat causing this issue:
```

    void process(final Mat m, final ResultsCallback callback, final WeakReference<Context> context) {
        if (!mHandler.hasMessages(10) && isProcessing.compareAndSet(false, true)) {
            HashMap<String, Object> map = new HashMap<>();
            // map.put("m", m.clone()); // doing-a-deep-copy-causes-memory-leak
            ...
        }
    }
```

```
--------- beginning of crash
09-17 19:00:41.571 9169-9514/com.app E/AndroidRuntime: FATAL EXCEPTION: Thread-2189
    Process: com.app, PID: 9169
    Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
    CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.4) /build/3_4-contrib_pack-contrib-android/opencv/modules/core/src/alloc.cpp:55: error: (-4:Insufficient memory) Failed to allocate 1382400 bytes in function 'void* cv::OutOfMemoryError(size_t)'
    ]
        at org.opencv.core.Mat.n_clone(Native Method)
        at org.opencv.core.Mat.clone(Mat.java:219)
        at com.app.react.spo2.SPOCalc.process(SPOCalc.java:149)
        at com.app.react.spo2.SPOCameraView$1.onCameraFrame(SPOCameraView.java:82)
        at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:392)
        at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:373)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by RobertSasak** [comment]
Sounds like your device does not have enough memory. What device do you test on?
